# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4d633a7ae127fe4b5622b87b14072d80"
organization_id = "145138106"
name = "Customer Accounts Wishlist"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,customer_write_customers,write_customers,customer_read_orders,unauthenticated_read_product_listings,unauthenticated_read_product_publications,unauthenticated_read_product_tags,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
